services:
  server:
    build: .
    env_file: app-example.env
    ports:
      - 8080:8080
    environment:
      - ENV=${ENV}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - DB_URL=postgres://${PGUSER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:latest
    env_file: db-example.env
    restart: always
    ports:
      - 5432:5432
    environment:
      - PGUSER=${PGUSER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 1s
      retries: 5